# MSU Maintenance — start SQL Server in Docker, create DB, install ODBC, bootstrap schema.
# Requires: Docker Desktop, winget (for ODBC driver), Python 3.10+ for bootstrap.
# Run from repo: powershell -ExecutionPolicy Bypass -File msu_maintenance_system/scripts/setup_sql_server.ps1

param(
    [string]$SaPassword = 'MsuSqlSetup!2026Strong',
    [string]$DbName = 'CentralServices_AM_DB',
    [string]$DbServer = 'localhost',
    [switch]$SkipOdbc,
    [switch]$SkipBootstrap
)

$ErrorActionPreference = 'Stop'

$MsuRoot = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path (Join-Path $MsuRoot 'config.py'))) {
    Write-Host "Expected config.py in $MsuRoot (run the script from the repo as documented)."
    exit 1
}
$RepoRoot = Split-Path -Parent $MsuRoot

$ComposeFile = Join-Path $RepoRoot 'docker-compose.yml'
if (-not (Test-Path $ComposeFile)) {
    Write-Host "docker-compose.yml not found at $ComposeFile"
    exit 1
}

Write-Host "=== MSU SQL Server setup ===" -ForegroundColor Cyan
Write-Host "Repo root: $RepoRoot"
Write-Host "App root:  $MsuRoot"

if (-not $SkipOdbc) {
    Write-Host "`n[1/5] ODBC Driver 18 for SQL Server..."
    $have = Get-OdbcDriver -Name '*SQL Server*' -ErrorAction SilentlyContinue | Where-Object { $_.Name -eq 'ODBC Driver 18 for SQL Server' }
    if (-not $have) {
        winget install --id Microsoft.msodbcsql.18 --exact --silent --accept-package-agreements --accept-source-agreements
    } else {
        Write-Host "Already installed."
    }
}

Write-Host "`n[2/5] Starting SQL Server container (msu-mssql)..."
Push-Location $RepoRoot
try {
    docker compose up -d mssql
    if ($LASTEXITCODE -ne 0) { throw "docker compose failed" }
} finally {
    Pop-Location
}

Write-Host "`n[3/5] Waiting for SQL Server to accept connections..."
$sqlcmdPaths = @(
    '/opt/mssql-tools18/bin/sqlcmd',
    '/opt/mssql-tools/bin/sqlcmd'
)
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    foreach ($sqlcmd in $sqlcmdPaths) {
        docker exec msu-mssql $sqlcmd -S localhost -U sa -P $SaPassword -C -Q "SELECT 1" 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            $ready = $true
            break
        }
    }
    if ($ready) { break }
    Start-Sleep -Seconds 2
}
if (-not $ready) {
    Write-Host "SQL Server did not become ready in time. Check: docker logs msu-mssql"
    exit 1
}

Write-Host "`n[4/5] Creating database $DbName if missing..."
$createSql = "IF DB_ID(N'$DbName') IS NULL BEGIN CREATE DATABASE [$DbName]; END"
$created = $false
foreach ($sqlcmd in $sqlcmdPaths) {
    docker exec msu-mssql $sqlcmd -S localhost -U sa -P $SaPassword -C -Q $createSql 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
        $created = $true
        break
    }
}
if (-not $created) {
    Write-Host "Failed to create database."
    exit 1
}

$dataDir = Join-Path $env:LOCALAPPDATA 'MSUMaintenance'
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
$envFile = Join-Path $dataDir '.env'

$secret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 48 | ForEach-Object { [char]$_ })

$envContent = @"
# Generated by setup_sql_server.ps1 — SQL Server in Docker (dev). Review before production.
FLASK_ENV=development
USE_SQLITE=0
SECRET_KEY=$secret
DB_SERVER=$DbServer
DB_NAME=$DbName
DB_USER=sa
DB_PASSWORD=$SaPassword
# MSU_DEMO_PASSWORD=ChangeMeAfterClone123!
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8
Write-Host "Wrote $envFile"

if ($SkipBootstrap) {
    Write-Host "`nSkipped Python bootstrap (-SkipBootstrap). From $MsuRoot run:"
    Write-Host '  python scripts/bootstrap_mssql_schema.py'
    exit 0
}

Write-Host "`n[5/5] Bootstrapping schema (venv / pip)..."
function Get-PythonExecutable {
    $skip = [regex]::Escape('WindowsApps')
    foreach ($name in @('python', 'python3')) {
        $cmd = Get-Command $name -ErrorAction SilentlyContinue
        if ($cmd -and $cmd.Source -notmatch $skip) {
            try {
                $null = & $name -c "import sys; print(sys.executable)" 2>$null
                if ($LASTEXITCODE -eq 0) { return $name.Trim() }
            } catch { }
        }
    }
    foreach ($path in @(
        "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python310\python.exe"
    )) {
        if (Test-Path $path) { return $path }
    }
    return $null
}

$py = Get-PythonExecutable
if (-not $py) {
    Write-Host "Python not found. Install Python 3.10+ and re-run, or run bootstrap_mssql_schema.py manually."
    exit 1
}

$venvDir = Join-Path $MsuRoot '.venv'
if (-not (Test-Path $venvDir)) {
    & $py -m venv $venvDir
}
$pip = Join-Path $venvDir 'Scripts\pip.exe'
$python = Join-Path $venvDir 'Scripts\python.exe'
& $pip install --upgrade pip -q
& $pip install python-dotenv flask flask-sqlalchemy flask-login flask-migrate flask-limiter flask-jwt-extended flask-wtf flask-talisman redis celery pyodbc pydantic email-validator limits ordered-set rich blinker werkzeug sqlalchemy alembic -q
if ($LASTEXITCODE -ne 0) {
    Write-Host "pip install failed; install requirements.txt in $venvDir and run:"
    Write-Host "  python scripts/bootstrap_mssql_schema.py"
    exit 1
}

$env:USE_SQLITE = '0'
$env:DB_SERVER = $DbServer
$env:DB_NAME = $DbName
$env:DB_USER = 'sa'
$env:DB_PASSWORD = $SaPassword
$env:SECRET_KEY = $secret
Push-Location $MsuRoot
try {
    & $python scripts/bootstrap_mssql_schema.py
    if ($LASTEXITCODE -ne 0) { throw "bootstrap failed" }
} finally {
    Pop-Location
}

Write-Host "`nDone. SQL Server: $DbServer / $DbName (sa)" -ForegroundColor Green
Write-Host "Config: $envFile"
Write-Host "Start app: cd `"$MsuRoot`"; .\scripts\start.ps1"
Write-Host "Python loads %LOCALAPPDATA%\MSUMaintenance\.env last (overrides) so USE_SQLITE=0 applies."
